export const Letters = (numberToReturn=48) => {
        return [
            {code: 0x0391, desc: 'Alpha'},
            {code: 0x0392, desc: 'Beta'},
            {code: 0x0393, desc: 'Gamma'},
            {code: 0x0394, desc: 'Delta'},
            {code: 0x0395, desc: 'Epsilon'},
            {code: 0x0396, desc: 'Zeta'},
            {code: 0x0397, desc: 'Eta'},
            {code: 0x0398, desc: 'Theta'},
            {code: 0x0399, desc: 'Iota'},
            {code: 0x039A, desc: 'Kappa'},
            {code: 0x039B, desc: 'Lambda'},
            {code: 0x039C, desc: 'Mu'},
            {code: 0x039D, desc: 'Nu'},
            {code: 0x039E, desc: 'Xi'},
            {code: 0x039F, desc: 'Omicron'},
            {code: 0x03A0, desc: 'Pi'},
            {code: 0x03A1, desc: 'Rho'},
            {code: 0x03A3, desc: 'Sigma'},
            {code: 0x03A4, desc: 'Tau'},
            {code: 0x03A5, desc: 'Upsilon'},
            {code: 0x03A6, desc: 'Phi'},
            {code: 0x03A7, desc: 'Chi'},
            {code: 0x03A8, desc: 'Psi'},
            {code: 0x03A9, desc: 'Omega'},
            {code: 0x03B1, desc: 'alpha'},
            {code: 0x03B2, desc: 'beta'},
            {code: 0x03B3, desc: 'gamma'},
            {code: 0x03B4, desc: 'delta'},
            {code: 0x03B5, desc: 'epsilon'},
            {code: 0x03B6, desc: 'zeta'},
            {code: 0x03B7, desc: 'eta'},
            {code: 0x03B8, desc: 'theta'},
            {code: 0x03B9, desc: 'iota'},
            {code: 0x03BA, desc: 'kappa'},
            {code: 0x03BB, desc: 'lambda'},
            {code: 0x03BC, desc: 'mu'},
            {code: 0x03BD, desc: 'nu'},
            {code: 0x03BE, desc: 'xi'},
            {code: 0x03BF, desc: 'omicron'},
            {code: 0x03C0, desc: 'pi'},
            {code: 0x03C1, desc: 'rho'},
            {code: 0x03C3, desc: 'sigma'},
            {code: 0x03C4, desc: 'tau'},
            {code: 0x03C5, desc: 'upsilon'},
            {code: 0x03C6, desc: 'phi'},
            {code: 0x03C7, desc: 'chi'},
            {code: 0x03C8, desc: 'psi'},
            {code: 0x03C9, desc: 'omega'}
        ];
};

